name: CI of my_flask_site v0.2.0
on:
  push:
    branches: [ master ]     
  workflow_dispatch:
   
jobs: 
  build:  
    runs-on: ubuntu-latest  
    steps:
         
      - name: Login DockerHub
        uses: docker/login-action@v1  
        with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      
      - name: Git clone my repo
        uses: actions/checkout@v2
      - run: ls -la
      
                
       
      - name: Build docker image and push to docker regisrty
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_IMAGE }}
          docker ps -a
          docker images
        
           
      - name: Pull and Run
        uses: appleboy/ssh-action@master
        with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.REMOTE_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.SSH_PORT }}
         script: |
          whoami
          ls -la
          docker ps -a
          docker container stop my_site
          docker container rm -f my_site
          docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password ${{ secrets.DOCKERHUB_TOKEN }} 
          docker pull ${{ secrets.DOCKER_IMAGE }}
          docker container run -d -p 8888:8888 --name my_site ${{ secrets.DOCKER_IMAGE }}
     
